import { Table } from "react-bootstrap";
function Users() {
  return (
        <Table responsive="sm">
          <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>id</td>
              <td>String</td>
              <td>
                The id of the user. Automatically generated by GAE Datastore
              </td>
            </tr>
            <tr>
              <td>token_id</td>
              <td>String</td>
              <td>
                Automatically generated upon logging in. Used to uniquely
                identify users after authenticating protected resources with JWT
              </td>
            </tr>
            <tr>
              <td>boats</td>
              <td>Array</td>
              <td>
                Specifies user owned boats with boat id and self-link to URL for
                boat object in Datastore.
              </td>
            </tr>
            <tr>
              <td>self</td>
              <td>String</td>
              <td>URL to the current user</td>
            </tr>
          </tbody>
        </Table>
  );
}

export default Users;
